### ISSUE TITLE
Setting MGOS_DEBUG_UART to 1 breaks rpc-uart

### ISSUE THREAD

**Issue by zdila** [mongoose-os-libs/rpc-uart#2]
I am using mos 2.15.0.

If trivial firmware is compiled with `mos build --platform esp8266 --local --clean --build-var MGOS_DEBUG_UART:1` then RPC over UART (eg. `mos config-get`) doesn’t work (timeouts).

AFAIK this wasn’t case in 2.14.0.

I think `MGOS_DEBUG_UART` shouldn’t influence non-debug functionality.

**Comment by rojer** [comment]
will take a look

**Comment by rojer** [comment]
tried to reproduce and could not. debug out put can be fully redirected to UART1 like this:

```yaml
config_schema:
  - ["debug.stdout_uart", 1]
  - ["debug.stderr_uart", 1]

build_vars:
  MGOS_DEBUG_UART: 1
```

but RPC on UART0 will still work:

```
$ mos ls
conf0.json
```
